[build]
  command = "npm run build:css:min && npm run build:react"
  publish = "public"

# Enable Pretty URLs
[processing]
  skip_processing = false

[processing.html]
  pretty_urls = true

# Production API Proxy to Render Backend
[[redirects]]
  from = "/api/*"
  to = "https://transitly-api.onrender.com/api/:splat"
  status = 200
  force = true

# React Single Page Application
[[redirects]]
  from = "/app/*"
  to = "/dist/index.html"
  status = 200

# Root fallback to /pages/index.html
[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200
